---
- name: Setup Camunda BPM Run
  hosts: servers
  become: yes
  vars_files:
    - vers.yml
  tasks:
    - name: Ensure dependencies are installed
      apt:
        name: wget
        state: present

    - name: Create Camunda directory
      file:
        path: "{{ camunda_dir }}"
        state: directory

    - name: Download Camunda BPM Run
      get_url:
        url: "{{ camunda_url }}"
        dest: "{{ download_dest }}"

    - name: Extract Camunda BPM Run
      unarchive:
        src: "{{ download_dest }}"
        dest: "{{ camunda_dir }}"
        remote_src: yes

    - name: Install OpenJDK 17
      apt:
        name: openjdk-17-jdk
        state: present

    - name: Set JAVA_HOME
      lineinfile:
        path: /etc/environment
        line: "{{ java_home }}"
        create: yes
        state: present

    - name: Reload environment variables
      shell: 'export $(cat /etc/environment | xargs)'

    - name: List directory contents after extraction
      command: ls -la "{{ camunda_dir }}"
      register: camunda_dir_contents

    - name: Debug directory contents
      debug:
        msg: "{{ camunda_dir_contents.stdout_lines }}"

    - name: Change working directory ownership
      file:
        path: "{{ camunda_dir }}"
        state: directory
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        mode: '0755'

    # Comment out the task for setting port until we identify the correct configuration file
    #- name: Set Camunda to run on port 9090
    #  lineinfile:
    #    path: /opt/camunda/configuration/default.yml
    #    regexp: 'port: 8080'
    #    line: 'port: 9090'
    #    state: present

    - name: Start Camunda BPM Run
      shell: |
        cd "{{ camunda_dir }}"
        ./start.sh
      args:
        chdir: "{{ camunda_dir }}"

    - name: Verify Java version
      command: java -version
      register: java_version

    - name: Debug Java version
      debug:
        msg: "{{ java_version.stdout }}"
